// <auto-generated />
using System;
using BookLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookLibrary.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookLibrary.Data.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_name");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImage")
                        .HasColumnType("text")
                        .HasColumnName("cover_image");

                    b.Property<string>("CoverType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cover_type");

                    b.Property<DateOnly?>("DateRead")
                        .HasColumnType("date")
                        .HasColumnName("date_read");

                    b.Property<bool>("HasBeenRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_been_read");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("PagesCount")
                        .HasColumnType("integer")
                        .HasColumnName("pages_count");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("publisher_id");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("volume_number");

                    b.HasKey("Id");

                    b.HasIndex("CoverType")
                        .HasDatabaseName("ix_books_cover_type");

                    b.HasIndex("PublisherId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_books_type");

                    b.HasIndex("Title", "VolumeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_books_title_volume_number");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Биографии и мемуары"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Биология"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Культура и искусство"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Лженаука"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Медицина и биология человека"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Политика и история"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Поп-культура и миры"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Саморазвитие и коммуникация"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Спорт"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Тру-крайм"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Фольклор и мифология"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Экономика и статистика"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Алгоритмы"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Архитектура компьютера"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Операционные системы"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Компьютерные сети"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Computer Science (общее)"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Базы данных"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Компьютерная безопасность"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Инструменты"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Проектирование и архитектура"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Микросервисы"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ООП"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Паттерны проектирования"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Рефакторинг"
                        },
                        new
                        {
                            Id = 28,
                            Name = "API"
                        },
                        new
                        {
                            Id = 29,
                            Name = "System Design"
                        },
                        new
                        {
                            Id = 30,
                            Name = "DDD и моделирование данных"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Саморазвитие в IT"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Тестирование"
                        },
                        new
                        {
                            Id = 33,
                            Name = "C# и .NET"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Go"
                        },
                        new
                        {
                            Id = 36,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Художественная литература"
                        });
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_publishers_name");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "АСТ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Эксмо"
                        },
                        new
                        {
                            Id = 3,
                            Name = "МИФ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Альпина Паблишер"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Альпина Нон-фикшн"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Азбука"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Corpus"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ad Marginem"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Livebook"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Individuum"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Питер"
                        },
                        new
                        {
                            Id = 12,
                            Name = "ДМК Пресс"
                        },
                        new
                        {
                            Id = 13,
                            Name = "O'Reilly Media"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Manning Publications"
                        },
                        new
                        {
                            Id = 15,
                            Name = "No Starch Press"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Addison-Wesley"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pearson"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Apress"
                        });
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentSeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ParentSeriesId")
                        .HasDatabaseName("ix_series_parent_series_id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_series_title");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("work_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_works_book_id");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Books_Categories", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.HasKey("BooksId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Books_Categories");
                });

            modelBuilder.Entity("Works_Authors", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("integer");

                    b.Property<int>("WorksId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorsId", "WorksId");

                    b.HasIndex("WorksId");

                    b.ToTable("Works_Authors");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Book", b =>
                {
                    b.HasOne("BookLibrary.Data.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLibrary.Data.Entities.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId");

                    b.Navigation("Publisher");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Series", b =>
                {
                    b.HasOne("BookLibrary.Data.Entities.Series", "ParentSeries")
                        .WithMany("SubSeries")
                        .HasForeignKey("ParentSeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentSeries");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Work", b =>
                {
                    b.HasOne("BookLibrary.Data.Entities.Book", "Book")
                        .WithMany("Works")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Books_Categories", b =>
                {
                    b.HasOne("BookLibrary.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.Data.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Works_Authors", b =>
                {
                    b.HasOne("BookLibrary.Data.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.Data.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Book", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Series", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("SubSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
